export enum MessageType {
  Attack = 'Attack',
  AttackResponse = 'AttackResponse',
  GameOver = 'GameOver',
  GameOverResponse = 'GameOverResponse',
  GameStart = 'GameStart',
  GameStartResponse = 'GameStartResponse',
  Username = 'Username',
  UsernameResponse = 'UsernameResponse',
  SaveGameRequest = "SaveGameRequest",
  SaveGame = 'SaveGame',
  SaveGameResponse = 'SaveGameResponse',
  Ready = 'Ready',
  ReadyResponse = 'ReadyResponse',
}
